// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'flutter_clevit_task';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String EBGARAMOND_BOLD = 'EBGaramond-Bold';
  static const String EBGARAMOND_BOLDITALIC = 'EBGaramond-BoldItalic';
  static const String EBGARAMOND_EXTRABOLD = 'EBGaramond-ExtraBold';
  static const String EBGARAMOND_EXTRABOLDITALIC = 'EBGaramond-ExtraBoldItalic';
  static const String EBGARAMOND_ITALIC = 'EBGaramond-Italic';
  static const String EBGARAMOND_ITALIC_VARIABLEFONT_WGHT_0 = 'EBGaramond-Italic-VariableFont_wght_0';
  static const String EBGARAMOND_MEDIUM = 'EBGaramond-Medium';
  static const String EBGARAMOND_MEDIUMITALIC = 'EBGaramond-MediumItalic';
  static const String EBGARAMOND_REGULAR = 'EBGaramond-Regular';
  static const String EBGARAMOND_SEMIBOLD = 'EBGaramond-SemiBold';
  static const String EBGARAMOND_SEMIBOLDITALIC = 'EBGaramond-SemiBoldItalic';
  static const String EBGARAMOND_VARIABLEFONT_WGHT_0 = 'EBGaramond-VariableFont_wght_0';
}
